targets:
  $default:
    builders:
      flutter_foundation_models_gen|generable:
        enabled: true

builders:
  generable:
    import: "package:flutter_foundation_models_gen/builder.dart"
    builder_factories: ["generableBuilder"]
    build_extensions: { ".dart": [".generable.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
