/// A wrapper for content generated by the language model.
///
/// [GeneratedContent] wraps the raw output from the model, which can be
/// a primitive value, a Map, or a List depending on the generation schema.
///
/// Use the generated `fromGeneratedContent` methods to convert this into
/// typed Dart objects:
///
/// ```dart
/// final content = await session.respondToWithSchema(
///   "Generate a user profile",
///   schema: $UserProfileGenerable.generationSchema,
/// );
///
/// // Convert to typed object
/// final profile = $UserProfileGenerable.fromGeneratedContent(content);
/// print(profile.name); // Typed access
/// ```
///
/// For streaming responses, use `fromPartialGeneratedContent`:
///
/// ```dart
/// stream.listen((partialContent) {
///   final partial = $UserProfileGenerable.fromPartialGeneratedContent(partialContent);
///   print(partial.name ?? "Loading..."); // Fields may be null
/// });
/// ```
extension type GeneratedContent(dynamic value) {}

/// Interface for types that can be converted to [GeneratedContent].
///
/// Classes annotated with @Generable automatically implement this via
/// the generated `toGeneratedContent()` extension method.
abstract class ConvertibleToGeneratedContent {
  /// Converts this object to [GeneratedContent] for use with the model.
  GeneratedContent toGeneratedContent();
}
